framework:
    messenger:
        # failure_transport: failed   # ← zakomentuj
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            # failed: ...             # ← zakomentuj
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: []
        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
