# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Command\CreateTenantCommand:
        arguments:
            $masterEm: '@doctrine.orm.master_entity_manager'

    App\Command\CreateUserCommand:
        arguments:
            $em: '@doctrine.orm.tenant_entity_manager'

    App\EventListener\TenantListener:
        arguments:
            $tenantConnection: '@doctrine.dbal.tenant_connection'
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 255 }
    App\Controller\Api\SuperadminController:
        arguments:
            $superadminToken: '%env(SUPERADMIN_API_TOKEN)%'
    App\EventListener\AdminEnabledListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 100 }
